<?php
require_once __DIR__ . '/includes/admin_auth.php';
require_once __DIR__ . '/includes/app_header.php';
require_admin();
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/admin_schema.php';
ensure_units_table($pdo);
$errors=[];$editing=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='delete'){ $id=(int)($_POST['id']??0); if($id>0){$stmt=$pdo->prepare('DELETE FROM measurement_units WHERE id=:id');$stmt->execute(['id'=>$id]);} header('Location: admin_units.php'); exit; }
 $id=(int)($_POST['id']??0); $full=trim($_POST['full_name']??''); $short=trim($_POST['short_name']??''); $note=trim($_POST['note']??''); $active=isset($_POST['is_active'])?1:0;
 if($full===''){$errors[]='Укажите полное название.';} if($short===''){$errors[]='Укажите сокращенное название.';}
 if(!$errors){$params=['full_name'=>$full,'short_name'=>$short,'note'=>$note?:null,'is_active'=>$active]; if($action==='update'&&$id>0){$params['id']=$id;$stmt=$pdo->prepare('UPDATE measurement_units SET full_name=:full_name, short_name=:short_name, note=:note, is_active=:is_active WHERE id=:id');}else{$stmt=$pdo->prepare('INSERT INTO measurement_units (full_name, short_name, note, is_active) VALUES (:full_name,:short_name,:note,:is_active)');}$stmt->execute($params); header('Location: admin_units.php'); exit;}
}
$editId=(int)($_GET['edit']??0); if($editId>0){$stmt=$pdo->prepare('SELECT * FROM measurement_units WHERE id=:id');$stmt->execute(['id'=>$editId]);$editing=$stmt->fetch()?:null;}
$units=$pdo->query('SELECT * FROM measurement_units ORDER BY is_active DESC, full_name ASC')->fetchAll();
?>
<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Единицы измерения</title><style>
body{font-family:'Inter',Arial,sans-serif;background:#f5f7fb;margin:0;color:#1f2937}.header{display:flex;align-items:center;gap:16px;flex-wrap:wrap;background:radial-gradient(circle at 10% 10%,rgba(59,130,246,.35),transparent 32%),linear-gradient(120deg,#0f172a,#1e3a8a 58%,#0f766e);color:#fff;padding:22px 36px 30px;box-shadow:0 18px 45px rgba(15,23,42,.18)}.header a{color:#dbeafe;font-weight:700;text-decoration:none;margin-right:16px}.container{max-width:1120px;margin:28px auto;padding:0 20px}.panel{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:22px;margin-bottom:24px;box-shadow:0 8px 24px rgba(15,23,42,.06)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}label{display:block;font-weight:600;margin-bottom:6px}input,textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5e1;border-radius:8px}input[type=checkbox]{width:auto}button,.button{border:0;border-radius:8px;padding:10px 14px;background:#2563eb;color:#fff;text-decoration:none;cursor:pointer;display:inline-block}.button.secondary{background:#64748b}button.danger{background:#dc2626}table{width:100%;border-collapse:collapse;background:#fff}th,td{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{background:#f8fafc}.errors{background:#fee2e2;color:#991b1b;padding:12px;border-radius:8px}.actions{display:flex;gap:8px;flex-wrap:wrap}.status{font-weight:700}
</style>
<?php echo app_header_styles(); ?></head><body><?php render_app_header(); ?>
<main class="container"><section class="panel"><h2><?php echo $editing?'Редактировать единицу':'Добавить единицу'; ?></h2><?php if($errors):?><div class="errors"><?php echo e(implode(' ',$errors));?></div><?php endif;?><form method="post"><input type="hidden" name="action" value="<?php echo $editing?'update':'create';?>"><input type="hidden" name="id" value="<?php echo e((string)($editing['id']??''));?>"><div class="grid"><div><label for="full_name">Полное название</label><input id="full_name" name="full_name" required value="<?php echo e((string)($editing['full_name']??''));?>"></div><div><label for="short_name">Сокращенное название</label><input id="short_name" name="short_name" required value="<?php echo e((string)($editing['short_name']??''));?>"></div></div><p><label for="note">Примечание</label><textarea id="note" name="note"><?php echo e((string)($editing['note']??''));?></textarea></p><p><label><input type="checkbox" name="is_active" <?php echo !isset($editing['is_active'])||(int)$editing['is_active']===1?'checked':'';?>> Активно</label></p><button type="submit">Сохранить</button> <?php if($editing):?><a class="button secondary" href="admin_units.php">Отмена</a><?php endif;?></form></section><section class="panel"><h2>Список единиц измерения</h2><table><thead><tr><th>Полное название</th><th>Сокращенное название</th><th>Примечание</th><th>Активно</th><th>Действия</th></tr></thead><tbody><?php foreach($units as $u):?><tr><td><?php echo e($u['full_name']);?></td><td><?php echo e($u['short_name']);?></td><td><?php echo e((string)($u['note']??''));?></td><td class="status"><?php echo (int)$u['is_active']===1?'Да':'Нет';?></td><td class="actions"><a class="button secondary" href="admin_units.php?edit=<?php echo e((string)$u['id']);?>">Изменить</a><form method="post" onsubmit="return confirm('Удалить единицу измерения?');"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?php echo e((string)$u['id']);?>"><button class="danger" type="submit">Удалить</button></form></td></tr><?php endforeach;?><?php if(!$units):?><tr><td colspan="5">Единицы измерения пока не добавлены.</td></tr><?php endif;?></tbody></table></section></main></body></html>
