const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const page = fs.readFileSync(path.join(root, 'calculator_septic.php'), 'utf8');
const integration = fs.readFileSync(path.join(__dirname, 'shower_partition_page.js'), 'utf8');

assert.match(page, /id="shower-config"/, 'Форма душевой перегородки должна присутствовать');
assert.match(page, /<label for="object_name">Объект<\/label><input id="object_name"[^>]*>/, 'Поле объекта должно быть необязательным');
assert.doesNotMatch(page.match(/<input id="object_name"[^>]*>/)?.[0] || '', /\brequired\b/, 'Поле объекта не должно блокировать расчёт');
assert.match(page, /id="panel_format_id"/, 'Должен быть выбор формата листа');
assert.match(page, /id="custom_sheet_width"/, 'Должен быть ввод ширины своего листа');
assert.match(page, /id="custom_sheet_height"/, 'Должен быть ввод длины своего листа');
assert.match(page, /id="shower_fascia_width"/, 'Должна быть ширина перемычки');
assert.match(page, /id="shower_fascia_height"/, 'Должна быть высота перемычки');
assert.match(page, /id="collection-field" class="hidden"/, 'Серия должна быть скрыта до выбора поставщика');
assert.match(page, /class="format-help"[\s\S]*role="tooltip"/, 'Подсказка формата должна открываться по иконке вопроса');
assert.match(page, /«Любой» подберёт формат с наименьшим отходом; «Свой» откроет ручной ввод\./, 'Подсказка должна объяснять автоматический и ручной форматы');
assert.doesNotMatch(page, /Выберите поставщика для фильтрации\./, 'Лишняя подсказка поставщика должна быть удалена');
assert.doesNotMatch(page, /3D-модель|трёхмерная модель/i, 'На странице не должно быть упоминаний 3D-модели');
assert.doesNotMatch(page, /id="shower-model-(?:trigger|modal)/, 'На странице не должно быть элементов 3D-модели');
assert.doesNotMatch(integration, /renderSchematic|openModelModal|shower-schematic-svg/, 'Интеграция не должна создавать 3D-модель');
assert.match(page, /scripts\/cutting_optimizer\.js/, 'Оптимизатор раскроя должен загружаться');
assert.match(page, /scripts\/shower_partition_calculator\.js/, 'Расчётный модуль должен загружаться');
assert.match(page, /scripts\/shower_partition_page\.js/, 'Интеграция страницы должна загружаться');
assert.match(page, /FROM price_list pl/, 'Каталог фурнитуры должен загружаться из базы');
assert.match(page, /fetch\('calculator_septic\.php'/, 'Сохранение должно отправляться в текущий обработчик');
assert.match(integration, /calculateShower/, 'Должен быть отдельный расчёт душевой перегородки');
assert.match(integration, /calculateBtn\.addEventListener\('click',[\s\S]*stopImmediatePropagation\(\)[\s\S]*calculateShower\(\)[\s\S]*true\)/, 'Кнопка должна запускать расчёт душевой вместо общего расчёта');
assert.match(integration, /serviceVolumes\(layout, panel\)/, 'Объём услуг должен рассчитываться по геометрии листов и изделий');
assert.match(integration, /service\.partition_type_id[\s\S]*typeSelect\.value/, 'В расчёт должны попадать базовые услуги выбранного типа перегородки');
assert.doesNotMatch(page, /shower-service-select|shower-service-add/, 'В форме калькулятора не должно быть добавления услуг до расчёта');
assert.doesNotMatch(integration, /extraServices|data-extra-service-volume/, 'Интеграция не должна добавлять дополнительные услуги до расчёта');
assert.match(page, /id="result-service-select"/, 'После расчёта должен быть выбор дополнительной услуги');
assert.match(page, /id="result-service-add"/, 'После расчёта должна быть кнопка добавления услуги');
assert.match(page, /LEFT JOIN panel_thicknesses pt ON pt\.id = s\.thickness_id/, 'Для списка дополнительных услуг должна загружаться толщина');
assert.match(page, /Код:[\s\S]*Толщ\.[\s\S]*h:[\s\S]*d:[\s\S]*Шаг:/, 'Дополнительные услуги должны различаться по характеристикам');
assert.match(integration, /estimatePanelLayout/, 'Расчёт должен использовать раскладку по листам');
assert.match(integration, /buildRequirements/, 'Расчёт должен формировать спецификацию фурнитуры');
assert.match(integration, /Группа: '[\s\S]*requirement\.groupLabel/, 'В строке роли должна отображаться выбранная группа товаров');
assert.match(page, /подставляется товар из выбранных производителя и серии/, 'Подсказка должна объяснять автовыбор из серии');
assert.match(page, /заменить любым товаром из той же группы/, 'Подсказка должна объяснять выбор из всех товаров группы');
assert.match(integration, /const matches = ShowerPartitionCalculator\.matchingFurniture\(requirement, furnitureCatalog\);/, 'Выпадающий список должен содержать все товары выбранной группы');
assert.match(integration, /matchingFurniture\(requirement, furnitureCatalog, preferredFilters\)/, 'Автовыбор должен учитывать производителя и серию');
assert.match(integration, /function resetRoleSelections\(\)[\s\S]*supplier_id'[\s\S]*resetRoleSelections\(\)[\s\S]*collection_id'[\s\S]*resetRoleSelections\(\)/, 'Смена производителя или серии должна заново выбирать товары по умолчанию');
assert.match(integration, /__auto__/, 'Должен поддерживаться автоматический выбор формата');
assert.match(integration, /__custom__/, 'Должен поддерживаться собственный формат');
assert.match(integration, /chooseBestPanelFormat/, 'Автоматический режим должен сравнивать существующие форматы');
assert.match(integration, /renderCollections/, 'Серии должны зависеть от поставщика');
assert.match(integration, /supplier_id'[\s\S]*addEventListener\('change'[\s\S]*renderCollections\(\)/, 'После выбора производителя должна появляться форма серии');

assert.match(page, /id="shower_layout_type"/, 'Должен быть выбор прямой, угловой и П-образной схемы');
assert.match(page, /value="built_in">Прямая</, 'Должна быть прямая схема');
assert.match(page, /value="corner">Угловая</, 'Должна быть угловая схема');
assert.match(page, /value="freestanding">П-образная</, 'Должна быть П-образная схема');

assert.match(page, /Количество кабин/, 'Поле должно называться «Количество кабин»');
assert.match(page, /id="shower_panel_count"/, 'Должно быть поле количества перегородок');
assert.match(page, /Количество перегородок/, 'Поле должно называться «Количество перегородок»');
assert.match(integration, /partitionCount: value\('shower_panel_count'\)/, 'Количество перегородок должно передаваться в расчёт');
assert.match(page, /Длина фасада, мм/, 'Поле должно называться «Длина фасада»');
assert.doesNotMatch(page, /id="shower_variant"/, 'Отдельного параметра фасадной части быть не должно');
assert.doesNotMatch(page, /id="shower_full_height"/, 'Параметра панели от пола до потолка быть не должно');
assert.doesNotMatch(page, />Верхняя труба</, 'Отдельного раздела верхней трубы быть не должно');
assert.match(page, /id="shower_top_support"[\s\S]*Труба[\s\S]*Профиль алюминиевый/, 'Без крепления к потолку должен выбираться тип верхней связи');
assert.match(integration, /partitionVariant/, 'Вариант фасада должен определяться типом перегородки');
assert.doesNotMatch(integration, /object_name'\)\.value\.trim\(\)/, 'Расчёт душевой перегородки не должен требовать объект');
assert.match(integration, /shower_ceiling_mount'\)\.addEventListener\('change', refresh\)/, 'Поле верхней связи должно обновляться при выборе крепления к потолку');
assert.match(integration, /shower-top-support-fields'\)\.classList\.toggle\('field-hidden', current\.ceilingMount !== 'none'\)/, 'Верхняя связь должна скрываться при креплении к потолку');

new Function(integration);
console.log('shower_partition_page.test.js: OK');
